version: 2

sources:
  - name: seimas
    schema: seimas_raw
    tables:
      - name: balsavimai
      - name: kadencijos
      - name: balsavimai__individualiai
      - name: seimo_nariai

models:
  - name: seimas
    schema: seimas_dbt
    tables:
    - name: balsavimai_individ
    - name: seimo_nariai